TRAINING_FOLDER_PATH = '/Volumes/Files/Georgetown/Advanced Machine Learning/Project Data/DataSet/'
SLASH = '/'
AUDIO_FILES_FOLDER = 'Audio Files'
FEATURES_FILES_FOLDER = 'Features'
AUDIO_FILES_SAMPLING_RATE = 16000
MFCC_COEFFICIENT_COUNT = 15

FEATURE_EXTRACTION_LOW_CUT_OFF_FREQUENCY = 100
FEATURE_EXTRACTION_HIGH_CUT_OFF_FREQUENCY = 3500
FEATURE_EXTRACTION_BAND_PASS_ORDER = 9

SAVE_MFCC_IMAGE = False