TRAINING_FOLDER_PATH = '/Volumes/Files/Georgetown/AdvancedMachineLearning/Project Data/DataSet/'
MODELS_OUTPUT_PATH = '/Volumes/Files/Georgetown/AdvancedMachineLearning/Project Output'
SLASH = '/'
AUDIO_FILES_FOLDER = 'Audio Files'
FEATURES_FILES_FOLDER = 'Features'
AUDIO_FILES_SAMPLING_RATE = 16000
MFCC_COEFFICIENT_COUNT = 20

FEATURE_EXTRACTION_LOW_CUT_OFF_FREQUENCY = 100
FEATURE_EXTRACTION_HIGH_CUT_OFF_FREQUENCY = 3500
FEATURE_EXTRACTION_BAND_PASS_ORDER = 9

SAVE_MFCC_IMAGE = False

TUPLE_INDEX_SUM = 0
TUPLE_INDEX_SUM_OF_SQUARES = 1
TUPLE_INDEX_MEAN = 0
TUPLE_INDEX_STD = 1
